version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-myfin-test
    ports:
      - 9100:80
      - 9104:443
    volumes:
      - ./data:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ../app:/app
    links:
      - php
  mysql:
    image: mysql:5.7.20
    container_name: mysql-myfin-test
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  php:
    build: ./php
    container_name: php-fpm-myfin-test
    expose:
      - 9000
    volumes:
      - ../app:/app
    links:
      - mysql
    environment:
      PHP_IDE_CONFIG: serverName=onliner-test
      XDEBUG_CONFIG: remote_host=<IP REMOTE HOST> remote_enable=On remote_autostart=1
          remote_connect_back=1 remote_port=9000 remote_log=/tmp/php7-xdebug.log
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myfintest
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin